name: Create Daily Scrum Issue
on: 
  schedule:
  - cron: "* * * * *"

jobs:
  create_scrum:
    name: scrum 
    runs-on: ubuntu-latest
    steps:
    
    - uses: imjohnbo/extract-issue-template-fields@v1
      id: extract
      with:
        path: .github/ISSUE_TEMPLATE/scrum.md

    - name: Today's date
      run: echo "TODAY=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

    - name: create new scrum issue
      uses: imjohnbo/issue-bot@v3
      with:
        labels: "scrum"
        title: ${{ env.TODAY }} Metalingo Scrum
        close-previous: true
