name: Create Daily Scrum Issue
on: 
  schedule:
  - cron: "0 * * * *"

jobs:
  create_scrum:
    name: scrum 
    runs-on: ubuntu-latest
    steps:

    - name: Today's date
      run: echo "TODAY=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

    - name: create new scrum issue
      uses: act/issue-bot@v3
      with:
        labels: "scrum"
        title: ${{ env.TODAY }} Metalingo Scrum
        close-previous: true
